Use [ScoreBoard]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Team](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [Team] [int] NOT NULL,
    [Score] [int] NOT NULL
 CONSTRAINT [PK_Score] PRIMARY KEY CLUSTERED,
 CONSTRAINT [FK_Team] FOREIGN KEY ([Team])
 REFERENCES [dbo].[Team] ([Number])
 ON DELETE CASCADE,
(
    [Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO